// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolBox.Services.SQLMonitor.EF;

namespace ToolBox.Services.SQLMonitor.Migrations
{
    [DbContext(typeof(SqlMonitorDbContext))]
    [Migration("20200302200951_Added_new_SqlQueries")]
    partial class Added_new_SqlQueries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.Database", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Databases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1d30005-182e-4274-8607-55dd7b3c4ed8"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(5639),
                            IsActive = true,
                            Name = "SqlMonitor",
                            ServerId = new Guid("59a75aa0-c958-4604-aa7b-3ffa21686c94"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(5670)
                        },
                        new
                        {
                            Id = new Guid("71801f2d-223b-4efe-adf9-2e7b59a80f80"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(8585),
                            IsActive = true,
                            Name = "SqlMonitor",
                            ServerId = new Guid("59a75aa0-c958-4604-aa7b-3ffa21686c94"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(8593)
                        },
                        new
                        {
                            Id = new Guid("3fb03345-59c3-4aca-adc7-19c476aca7c1"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(8675),
                            IsActive = true,
                            Name = "modeldb",
                            ServerId = new Guid("59a75aa0-c958-4604-aa7b-3ffa21686c94"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(8676)
                        },
                        new
                        {
                            Id = new Guid("93b86968-9da3-42ff-b1b7-85c91c6bb990"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(8719),
                            IsActive = true,
                            Name = "msdb",
                            ServerId = new Guid("59a75aa0-c958-4604-aa7b-3ffa21686c94"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(8721)
                        },
                        new
                        {
                            Id = new Guid("691dfcce-dec5-40c3-8d8b-6d3250a2121d"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(8744),
                            IsActive = true,
                            Name = "tempdb",
                            ServerId = new Guid("59a75aa0-c958-4604-aa7b-3ffa21686c94"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 876, DateTimeKind.Utc).AddTicks(8745)
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForServer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastInvokedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75db5b1d-a996-4523-90a9-33ac84eb7126"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 878, DateTimeKind.Utc).AddTicks(4264),
                            Interval = 5,
                            IsActive = true,
                            IsForServer = true,
                            LastInvokedDate = new DateTime(2020, 3, 2, 20, 9, 50, 878, DateTimeKind.Local).AddTicks(4889),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 878, DateTimeKind.Utc).AddTicks(4271)
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.ScheduleServer", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleId", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("ScheduleServer");

                    b.HasData(
                        new
                        {
                            ScheduleId = new Guid("75db5b1d-a996-4523-90a9-33ac84eb7126"),
                            ServerId = new Guid("59a75aa0-c958-4604-aa7b-3ffa21686c94")
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.ScheduleSqlQuery", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SqlQueryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleId", "SqlQueryId");

                    b.HasIndex("SqlQueryId");

                    b.ToTable("ScheduleSqlQuery");

                    b.HasData(
                        new
                        {
                            ScheduleId = new Guid("75db5b1d-a996-4523-90a9-33ac84eb7126"),
                            SqlQueryId = new Guid("56fd19f8-c997-4887-b6a1-5e9361e12f69")
                        },
                        new
                        {
                            ScheduleId = new Guid("75db5b1d-a996-4523-90a9-33ac84eb7126"),
                            SqlQueryId = new Guid("03e66313-3755-4190-a974-b053af085806")
                        },
                        new
                        {
                            ScheduleId = new Guid("75db5b1d-a996-4523-90a9-33ac84eb7126"),
                            SqlQueryId = new Guid("95c7f8e0-4c84-4f18-a4c2-5f7a77b00ad3")
                        },
                        new
                        {
                            ScheduleId = new Guid("75db5b1d-a996-4523-90a9-33ac84eb7126"),
                            SqlQueryId = new Guid("78fedfb9-3e4e-4658-ab63-897663bc3559")
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59a75aa0-c958-4604-aa7b-3ffa21686c94"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 874, DateTimeKind.Utc).AddTicks(6850),
                            Host = "localhost",
                            IsActive = true,
                            Login = "sa",
                            Name = "Sql monitor server",
                            Password = "Pass_w0rd12",
                            Port = 1465,
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 874, DateTimeKind.Utc).AddTicks(8577),
                            UserId = new Guid("d2b248e2-07a5-4d2c-b4d4-d933a84ee5f6")
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.SqlQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStoredProcedure")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SQLQueries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56fd19f8-c997-4887-b6a1-5e9361e12f69"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(6008),
                            Description = "The name of a server",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 0,
                            Query = "SELECT SERVERPROPERTY('Servername') as ServerName",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(6046)
                        },
                        new
                        {
                            Id = new Guid("03e66313-3755-4190-a974-b053af085806"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8115),
                            Description = "List of Database names in a server",
                            IsActive = true,
                            IsStoredProcedure = true,
                            Name = 1,
                            Query = "EXEC sp_databases",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8122)
                        },
                        new
                        {
                            Id = new Guid("95c7f8e0-4c84-4f18-a4c2-5f7a77b00ad3"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8167),
                            Description = "Needs to be executed with keyword use [DATABASE_NAME]. Database space information",
                            IsActive = true,
                            IsStoredProcedure = true,
                            Name = 3,
                            Query = "EXEC sp_spaceused @oneresultset = 1",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8168)
                        },
                        new
                        {
                            Id = new Guid("78fedfb9-3e4e-4658-ab63-897663bc3559"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8170),
                            Description = "Databases backup status",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 2,
                            Query = @"SELECT d.name AS 'DATABASE_Name',
                          MAX(CASE WHEN bu.TYPE = 'D' THEN bu.LastBackupDate END) AS 'Full DB Backup Status',
                          MAX(CASE WHEN bu.TYPE = 'I' THEN bu.LastBackupDate END) AS 'Differential DB Backup Status',
                          MAX(CASE WHEN bu.TYPE = 'L' THEN bu.LastBackupDate END) AS 'Transaction DB Backup Status',
                          CASE d.recovery_model WHEN 1 THEN 'Full' WHEN 2 THEN 'Bulk Logged' WHEN 3 THEN 'Simple' END RecoveryModel
                          FROM MASTER.sys.databases d
                          LEFT OUTER JOIN (SELECT database_name, TYPE, MAX(backup_start_date) AS LastBackupDate
                          FROM msdb.dbo.backupset
                          GROUP BY database_name, TYPE) AS bu ON d.name = bu.database_name
                          GROUP BY d.Name, d.recovery_model",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8171)
                        },
                        new
                        {
                            Id = new Guid("37f8d10d-6d71-4968-9145-4ed49e68b653"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8174),
                            Description = "Finding users that are connected to the server",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 4,
                            Query = @"SELECT login_name ,COUNT(session_id) AS session_count   
                          FROM sys.dm_exec_sessions
                          GROUP BY login_name; ",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8175)
                        },
                        new
                        {
                            Id = new Guid("0ee5ebee-a851-41a3-adbc-e7e7b4118cf8"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8177),
                            Description = "The most CPU consumed 20 queries",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 5,
                            Query = @"SELECT TOP 20 query_stats.query_hash AS 'Query Hash',   
	                        	SUM(query_stats.total_worker_time) / SUM(query_stats.execution_count) AS 'Avg CPU Time',  
	                        	MIN(query_stats.statement_text) AS 'Statement Text'  
	                        FROM   
	                        	(SELECT QS.*,   
	                        	SUBSTRING(ST.text, (QS.statement_start_offset/2) + 1,  
	                        	((CASE statement_end_offset   
	                        		WHEN -1 THEN DATALENGTH(ST.text)  
	                        		ELSE QS.statement_end_offset END   
	                        			- QS.statement_start_offset)/2) + 1) AS statement_text  
	                        	 FROM sys.dm_exec_query_stats AS QS  
	                        	 CROSS APPLY sys.dm_exec_sql_text(QS.sql_handle) as ST) as query_stats  
	                        GROUP BY query_stats.query_hash  
	                        ORDER BY 2 DESC;  
                        ",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8178)
                        },
                        new
                        {
                            Id = new Guid("27ec8cb9-71a2-44c7-8189-1c1f94b74e2f"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8188),
                            Description = "Memory usage",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 6,
                            Query = @"SELECT object_name, counter_name, cntr_value
                            FROM sys.dm_os_performance_counters
                            WHERE [object_name] LIKE '%Buffer Manager%'
                            AND [counter_name] in ('Page life expectancy','Free list stalls/sec',
                            'Page reads/sec')",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 9, 50, 877, DateTimeKind.Utc).AddTicks(8189)
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.Database", b =>
                {
                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.Server", "Server")
                        .WithMany("Databases")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.ScheduleServer", b =>
                {
                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.Schedule", "Schedule")
                        .WithMany("ScheduleServers")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.Server", "Server")
                        .WithMany("ScheduleServers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.ScheduleSqlQuery", b =>
                {
                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.Schedule", "Schedule")
                        .WithMany("ScheduleSqlQueries")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.SqlQuery", "SqlQuery")
                        .WithMany("ScheduleSqlQueries")
                        .HasForeignKey("SqlQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
