// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolBox.Services.SQLMonitor.EF;

namespace ToolBox.Services.SQLMonitor.Migrations
{
    [DbContext(typeof(SqlMonitorDbContext))]
    [Migration("20200302202453_Added_new_SqlQueries_Updated")]
    partial class Added_new_SqlQueries_Updated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.Database", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Databases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f085547b-3081-4d08-acbf-fc5495fefd0b"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(5898),
                            IsActive = true,
                            Name = "SqlMonitor",
                            ServerId = new Guid("bf736e19-1aeb-4205-850e-b15bfd9c1138"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(5923)
                        },
                        new
                        {
                            Id = new Guid("27df32e3-4cad-4ebf-a207-90061560d155"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(7863),
                            IsActive = true,
                            Name = "SqlMonitor",
                            ServerId = new Guid("bf736e19-1aeb-4205-850e-b15bfd9c1138"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(7868)
                        },
                        new
                        {
                            Id = new Guid("c2a03d2c-73dc-4598-b20f-76c28bcb0cec"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(7949),
                            IsActive = true,
                            Name = "modeldb",
                            ServerId = new Guid("bf736e19-1aeb-4205-850e-b15bfd9c1138"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(7950)
                        },
                        new
                        {
                            Id = new Guid("e5792303-30e6-4995-9e2d-6b135a0b45a2"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(7973),
                            IsActive = true,
                            Name = "msdb",
                            ServerId = new Guid("bf736e19-1aeb-4205-850e-b15bfd9c1138"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(7974)
                        },
                        new
                        {
                            Id = new Guid("6846fe3e-8f43-4686-9995-23760462f37b"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(7996),
                            IsActive = true,
                            Name = "tempdb",
                            ServerId = new Guid("bf736e19-1aeb-4205-850e-b15bfd9c1138"),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 864, DateTimeKind.Utc).AddTicks(7997)
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForServer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastInvokedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5445f44c-1055-4c51-b231-2be0ca64c2ab"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 866, DateTimeKind.Utc).AddTicks(3036),
                            Interval = 4,
                            IsActive = true,
                            IsForServer = true,
                            LastInvokedDate = new DateTime(2020, 3, 2, 20, 24, 52, 866, DateTimeKind.Local).AddTicks(3654),
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 866, DateTimeKind.Utc).AddTicks(3043)
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.ScheduleServer", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleId", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("ScheduleServer");

                    b.HasData(
                        new
                        {
                            ScheduleId = new Guid("5445f44c-1055-4c51-b231-2be0ca64c2ab"),
                            ServerId = new Guid("bf736e19-1aeb-4205-850e-b15bfd9c1138")
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.ScheduleSqlQuery", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SqlQueryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleId", "SqlQueryId");

                    b.HasIndex("SqlQueryId");

                    b.ToTable("ScheduleSqlQuery");

                    b.HasData(
                        new
                        {
                            ScheduleId = new Guid("5445f44c-1055-4c51-b231-2be0ca64c2ab"),
                            SqlQueryId = new Guid("5494a8a6-2405-4ce8-81a5-350e0bb20315")
                        },
                        new
                        {
                            ScheduleId = new Guid("5445f44c-1055-4c51-b231-2be0ca64c2ab"),
                            SqlQueryId = new Guid("59cc09b9-f281-4a33-ad49-f20ae7a7da38")
                        },
                        new
                        {
                            ScheduleId = new Guid("5445f44c-1055-4c51-b231-2be0ca64c2ab"),
                            SqlQueryId = new Guid("86f9424d-87cf-46f7-8346-9c676766b30a")
                        },
                        new
                        {
                            ScheduleId = new Guid("5445f44c-1055-4c51-b231-2be0ca64c2ab"),
                            SqlQueryId = new Guid("55b6f3a3-6729-424c-9c38-630d95bc71ea")
                        },
                        new
                        {
                            ScheduleId = new Guid("5445f44c-1055-4c51-b231-2be0ca64c2ab"),
                            SqlQueryId = new Guid("0baa8e48-34c0-48e1-9e91-2514d0a17f50")
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf736e19-1aeb-4205-850e-b15bfd9c1138"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 862, DateTimeKind.Utc).AddTicks(4219),
                            Host = "localhost",
                            IsActive = true,
                            Login = "sa",
                            Name = "Sql monitor server",
                            Password = "Pass_w0rd12",
                            Port = 1465,
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 862, DateTimeKind.Utc).AddTicks(6119),
                            UserId = new Guid("d2b248e2-07a5-4d2c-b4d4-d933a84ee5f6")
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.SqlQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStoredProcedure")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SQLQueries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5494a8a6-2405-4ce8-81a5-350e0bb20315"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6866),
                            Description = "List of Database names in a server",
                            IsActive = true,
                            IsStoredProcedure = true,
                            Name = 1,
                            Query = "EXEC sp_databases",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6871)
                        },
                        new
                        {
                            Id = new Guid("59cc09b9-f281-4a33-ad49-f20ae7a7da38"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6924),
                            Description = "Needs to be executed with keyword use [DATABASE_NAME]. Database space information",
                            IsActive = true,
                            IsStoredProcedure = true,
                            Name = 3,
                            Query = "EXEC sp_spaceused @oneresultset = 1",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6925)
                        },
                        new
                        {
                            Id = new Guid("86f9424d-87cf-46f7-8346-9c676766b30a"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6928),
                            Description = "Databases backup status",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 2,
                            Query = @"SELECT d.name AS 'DATABASE_Name',
                          MAX(CASE WHEN bu.TYPE = 'D' THEN bu.LastBackupDate END) AS 'Full DB Backup Status',
                          MAX(CASE WHEN bu.TYPE = 'I' THEN bu.LastBackupDate END) AS 'Differential DB Backup Status',
                          MAX(CASE WHEN bu.TYPE = 'L' THEN bu.LastBackupDate END) AS 'Transaction DB Backup Status',
                          CASE d.recovery_model WHEN 1 THEN 'Full' WHEN 2 THEN 'Bulk Logged' WHEN 3 THEN 'Simple' END RecoveryModel
                          FROM MASTER.sys.databases d
                          LEFT OUTER JOIN (SELECT database_name, TYPE, MAX(backup_start_date) AS LastBackupDate
                          FROM msdb.dbo.backupset
                          GROUP BY database_name, TYPE) AS bu ON d.name = bu.database_name
                          GROUP BY d.Name, d.recovery_model",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6929)
                        },
                        new
                        {
                            Id = new Guid("55b6f3a3-6729-424c-9c38-630d95bc71ea"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6931),
                            Description = "Finding users that are connected to the server",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 4,
                            Query = @"SELECT login_name ,COUNT(session_id) AS session_count   
                          FROM sys.dm_exec_sessions
                          GROUP BY login_name; ",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6932)
                        },
                        new
                        {
                            Id = new Guid("0baa8e48-34c0-48e1-9e91-2514d0a17f50"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6937),
                            Description = "Memory usage",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 6,
                            Query = @"SELECT object_name, counter_name, cntr_value
                            FROM sys.dm_os_performance_counters
                            WHERE [object_name] LIKE '%Buffer Manager%'
                            AND [counter_name] in ('Page life expectancy','Free list stalls/sec',
                            'Page reads/sec')",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6938)
                        },
                        new
                        {
                            Id = new Guid("01d70006-675f-43c3-9152-b98166780f49"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6934),
                            Description = "The most CPU consumed 20 queries",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 5,
                            Query = @"SELECT TOP 20 query_stats.query_hash AS 'Query Hash',   
	                        	SUM(query_stats.total_worker_time) / SUM(query_stats.execution_count) AS 'Avg CPU Time',  
	                        	MIN(query_stats.statement_text) AS 'Statement Text'  
	                        FROM   
	                        	(SELECT QS.*,   
	                        	SUBSTRING(ST.text, (QS.statement_start_offset/2) + 1,  
	                        	((CASE statement_end_offset   
	                        		WHEN -1 THEN DATALENGTH(ST.text)  
	                        		ELSE QS.statement_end_offset END   
	                        			- QS.statement_start_offset)/2) + 1) AS statement_text  
	                        	 FROM sys.dm_exec_query_stats AS QS  
	                        	 CROSS APPLY sys.dm_exec_sql_text(QS.sql_handle) as ST) as query_stats  
	                        GROUP BY query_stats.query_hash  
	                        ORDER BY 2 DESC;  
                        ",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(6935)
                        },
                        new
                        {
                            Id = new Guid("4cc67ee2-0d51-4eb7-9050-adc57fc06df3"),
                            CreatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(4594),
                            Description = "The name of a server",
                            IsActive = true,
                            IsStoredProcedure = false,
                            Name = 0,
                            Query = "SELECT SERVERPROPERTY('Servername') as ServerName",
                            UpdatedDate = new DateTime(2020, 3, 2, 20, 24, 52, 865, DateTimeKind.Utc).AddTicks(4621)
                        });
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.Database", b =>
                {
                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.Server", "Server")
                        .WithMany("Databases")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.ScheduleServer", b =>
                {
                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.Schedule", "Schedule")
                        .WithMany("ScheduleServers")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.Server", "Server")
                        .WithMany("ScheduleServers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToolBox.Services.SQLMonitor.Entities.ScheduleSqlQuery", b =>
                {
                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.Schedule", "Schedule")
                        .WithMany("ScheduleSqlQueries")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolBox.Services.SQLMonitor.Entities.SqlQuery", "SqlQuery")
                        .WithMany("ScheduleSqlQueries")
                        .HasForeignKey("SqlQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
