version: '3.4'

services:
  api:
    hostname: 'api'
    container_name: 'api'
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

  identity:
    hostname: 'identity'
    container_name: 'identity'
    ports:
      - 5010:5010
    restart: on-failure
    depends_on:
      - rabbitmq
      - identitydb
    links: 
      - rabbitmq
      - identitydb

  dbworker:
    hostname: 'dbworker'
    container_name: 'dbworker'
    ports:
      - 5030:5030
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
  
  notification:
    hostname: 'notification'
    container_name: 'notification'
    ports:
      - 5050:5050
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
  
  sqlmonitor:
    hostname: 'sqlmonitor'
    container_name: 'sqlmonitor'
    ports:
      - 5020:5020
    restart: on-failure
    depends_on:
      - rabbitmq
      - sqlmonitordb
    links: 
      - rabbitmq
      - sqlmonitordb

  rabbitmq:
    hostname: 'rabbitmq'
    container_name: 'rabbitmq'
    expose:
      - 5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    ports:
      - '5672:5672'

  identitydb:
    hostname: 'identitydb'
    container_name: 'identitydb'
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Pass_w0rd12"
    ports:
      - '1455:1433'

  sqlmonitordb:
    hostname: 'sqlmonitordb'
    container_name: 'sqlmonitordb'
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Pass_w0rd12"
    ports:
      - '1465:1433'